print('''I'm learning Git merge conflicts" to the console''')
name = input('Please enter your name:')
last_name = input('Please enter your last name:')
print('Hi, {} {}!'.format(name, last_name))
nick = input('Please enter your nickname')
print('Hi, {}!'.format(nick))